name: Node.js CI

on: 
  push:
    branches:
      - testCI      # 仅 testCI 分支的推送触发
    paths:
      - "src/**"  # 仅 src 目录下的文件变更触发[5,6](@ref)

jobs:
  build:

    # runs-on: ubuntu-latest
    runs-on: windows-latest
    
    strategy:
      matrix:
        node-version: [21.6.1]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
