name: apiSqlGateWay CI

on: 
  push:
    branches:
      - testCI      # 仅 testCI 分支的推送触发
    paths:
      - .github/workflows/ci.yml
      - "src/**"  # 仅 src 目录下的文件变更触发[5,6](@ref)
jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js 32-bit
      shell: powershell
      run: |
        $nodeVersion = "18.18.2"
        $nodeUrl = "https://nodejs.org/dist/v18.18.2/node-v18.18.2-x86.msi"
        Invoke-WebRequest -Uri $nodeUrl -OutFile node.msi
        Start-Process msiexec.exe -Wait -ArgumentList '/i node.msi /TARGETDIR=d:\a\NodeJS /quiet'
        $env:Path = "d:\a\NodeJS;" + $env:Path
        
        node -v
        node -p "process.arch" 
    - name: Test Node.js
      run: |
        dir "C:\Program Files (x86)"
        dir "d:\a"
        dir "d:\a\NodeJS"
        node -v
        node -p "process.arch" 
        npm -v
        npm install
        npm test