name: Install Node.js 18.18.2 32-bit on Windows
on:
  push:
    branches:
      - testCI
jobs:
  install-nodejs:
    runs-on: self-hosted
    steps:
      - name: env check
        shell: cmd
        run: dir "C:\Program Files"
      - name: env check
        shell: cmd
        run: dir "C:\Program Files(x86)"
      
      - name: check node install
        shell: cmd  
        run: |
          node -p "process.platform && process.arch"
          node --version  

      # - name: Install Chocolatey
      #   shell: powershell
      #   run: |
      #     Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))


      # - name: Install Node.js 18.18.2 32-bit
      #   shell: powershell
      #   # run: choco install nodejs --version 18.18.2 -ia "ARCH=32" -y
      #   run: choco install nodejs --version 18.18.2 --params="/InstallDir:C:\NodeJS_x86 /Architecture:x86" -y
  