
name: Windows Node.js 32-bit CI

on:  
  push:
    branches:
      - testCI      # 仅 testCI 分支的推送触发
    paths:
      - .github/workflows/testWinx86.yml
    

jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js 32-bit
      shell: powershell
      run: |
        $nodeVersion = "18.17.1"
        $nodeUrl = "https://nodejs.org/dist/v$nodeVersion/node-v$nodeVersion-x86.msi"
        Invoke-WebRequest -Uri $nodeUrl -OutFile node.msi
        Start-Process msiexec.exe -Wait -ArgumentList '/i node.msi /quiet'
        $env:Path += ";C:\Program Files (x86)\nodejs"

    - name: Test Node.js
      run: |
        node -p "process.arch"  # 应输出 'ia32'
        npm -v